### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#266]
Getting following error message:
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
java.lang.IllegalStateException: Could not find Object type
	at org.apache.flink.calcite.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at com.datasqrl.graphql.inference.SchemaInference.unwrapObjectType(SchemaInference.java:227)
	at com.datasqrl.graphql.inference.SchemaInference.inferObjectField(SchemaInference.java:153)
	at com.datasqrl.graphql.inference.SchemaInference.walkRel(SchemaInference.java:193)
	at com.datasqrl.graphql.inference.SchemaInference.walk(SchemaInference.java:184)
	at com.datasqrl.graphql.inference.SchemaInference.lambda$walkChildren$8(SchemaInference.java:176)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.datasqrl.graphql.inference.SchemaInference.walkChildren(SchemaInference.java:177)
	at com.datasqrl.graphql.inference.SchemaInference.inferObjectField(SchemaInference.java:162)
	at com.datasqrl.graphql.inference.SchemaInference.walkRel(SchemaInference.java:193)
	at com.datasqrl.graphql.inference.SchemaInference.walk(SchemaInference.java:184)
	at com.datasqrl.graphql.inference.SchemaInference.lambda$walkChildren$8(SchemaInference.java:176)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.datasqrl.graphql.inference.SchemaInference.walkChildren(SchemaInference.java:177)
	at com.datasqrl.graphql.inference.SchemaInference.inferObjectField(SchemaInference.java:162)
	at com.datasqrl.graphql.inference.SchemaInference.resolveQueryFromSchema(SchemaInference.java:120)
	at com.datasqrl.graphql.inference.SchemaInference.resolveQueries(SchemaInference.java:105)
	at com.datasqrl.graphql.inference.SchemaInference.lambda$accept$0(SchemaInference.java:84)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.datasqrl.graphql.inference.SchemaInference.accept(SchemaInference.java:84)
	at com.datasqrl.compile.Compiler.run(Compiler.java:137)
	at com.datasqrl.cmd.AbstractCompilerCommand.runCommand(AbstractCompilerCommand.java:108)
	at com.datasqrl.cmd.AbstractCommand.run(AbstractCommand.java:27)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.datasqrl.DatasqrlCMD.main(DatasqrlCMD.java:12)
[FATAL] Could not find Object type
```

For script:
```
--IMPORT metricapi.AddReading AS SensorReading;
IMPORT datasqrl.example.sensors.SensorReading; -- Import sensor data
IMPORT datasqrl.example.sensors.Sensors;
IMPORT time.endOfSecond;                -- Import time function
/* Aggregate sensor readings to second */
SecReading := SELECT sensorid, endOfSecond(time) as timeSec,
        avg(temperature) as temp FROM SensorReading
    GROUP BY sensorid, timeSec;
/* Create table of sensors and relate to readings */
Sensors := DISTINCT Sensors ON id  ORDER BY placed DESC;
Sensors.readings := JOIN SecReading r ON r.sensorid = @.id;
Sensors.lastHour := SELECT max(temp) as maxTemp, avg(temp) as avgTemp
                       FROM @.readings
                       WHERE timeSec >= now() - INTERVAL 1 HOUR;
/* Create table of machines with recent temperature */
Machine := SELECT machineid, max(temp) as maxTemp,
    avg(temp) as avgTemp
    FROM Sensors s JOIN s.readings
    WHERE timeSec >= now() - INTERVAL 1 HOUR
    GROUP BY machineid;

Machine.sensors := JOIN Sensors s ON s.machineid = @.machineid;

HighTemp := SELECT machineid, sensorid, temp, timeSec
            FROM Sensors s JOIN s.readings
            WHERE temp > 100;

EXPORT HighTemp TO print.tempWarning;
```

and GraphQL
```
type Query {
  Machine(machineid: Int): [Machine!]
  Sensors(id: Int!): Sensors!
}

type Machine {
  machineid: Int!
  maxTemp: Float!
  avgTemp: Float!
  sensors: [Sensors!]
}

type SecReading {
  timeSec: String!
  temp: Float!
}

type Sensors {
  id: Int!
  machineid: Int!
  placed: String!
  readings: [SecReadings!]
  lastHour: lastHour!
}

type lastHour {
  maxTemp: Float!
  avgTemp: Float!
}


type Mutation {
  AddReading(createReading: SensorReading!): CreateReading
}

input SensorReading {
  sensorid: Int!
  temperature: Float!
}

type CreateReading {
  _source_time: String!
  sensorid: Int!
}
```

**Comment by mbroecheler** [comment]
SecReadings does not exist
