### ISSUE TITLE
Unclear Error Message

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#267]
When a field is not present on the table, we get an error without source map:

```
com.datasqrl.parse.SqrlAstException: Could not find field: [time]
	at com.datasqrl.plan.local.transpile.AnalyzeExpression.visit(AnalyzeExpression.java:71)
	at com.datasqrl.plan.local.transpile.AnalyzeExpression.visit(AnalyzeExpression.java:22)
	at org.apache.calcite.sql.SqlIdentifier.accept(SqlIdentifier.java:320)
	at org.apache.calcite.sql.SqlOperator.acceptCall(SqlOperator.java:852)
	at org.apache.calcite.sql.util.SqlBasicVisitor.visit(SqlBasicVisitor.java:45)
	at com.datasqrl.plan.local.transpile.AnalyzeExpression.visit(AnalyzeExpression.java:54)
	at com.datasqrl.plan.local.transpile.AnalyzeExpression.visit(AnalyzeExpression.java:22)
	at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:139)
	at com.datasqrl.plan.local.transpile.AnalyzeExpression.visitAs(AnalyzeExpression.java:58)
	at com.datasqrl.plan.local.transpile.AnalyzeExpression.visit(AnalyzeExpression.java:45)
	at com.datasqrl.plan.local.transpile.AnalyzeExpression.visit(AnalyzeExpression.java:22)
	at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:139)
	at com.datasqrl.plan.local.transpile.AnalyzeStatement.visitExpr(AnalyzeStatement.java:678)
	at com.datasqrl.plan.local.transpile.AnalyzeStatement.visitSelectList(AnalyzeStatement.java:546)
	at com.datasqrl.plan.local.transpile.AnalyzeStatement.visitSelect(AnalyzeStatement.java:510)
	at com.datasqrl.plan.local.transpile.AnalyzeStatement.visit(AnalyzeStatement.java:141)
	at com.datasqrl.plan.local.transpile.AnalyzeStatement.accept(AnalyzeStatement.java:118)
	at com.datasqrl.plan.local.generate.Transpiler.lambda$createTransformer$1(Transpiler.java:78)
	at com.datasqrl.plan.local.generate.SqlTransformer.transform(SqlTransformer.java:26)
	at com.datasqrl.plan.local.generate.Transpiler.transpile(Transpiler.java:47)
	at com.datasqrl.plan.local.generate.AbstractStatementResolver.transpile(AbstractStatementResolver.java:36)
	at com.datasqrl.plan.local.generate.AbstractQueryStatementResolver.resolve(AbstractQueryStatementResolver.java:32)
	at com.datasqrl.plan.local.generate.StatementProcessor.visit(StatementProcessor.java:73)
	at com.datasqrl.plan.local.generate.StatementProcessor.visit(StatementProcessor.java:19)
	at org.apache.calcite.sql.QueryAssignment.accept(QueryAssignment.java:47)
	at com.datasqrl.plan.local.generate.Resolve.executeStatement(Resolve.java:63)
	at com.datasqrl.plan.local.generate.Resolve.lambda$planTablesHelper$1(Resolve.java:54)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.datasqrl.plan.local.generate.Resolve.planTablesHelper(Resolve.java:54)
	at com.datasqrl.plan.local.generate.Resolve.planTables(Resolve.java:43)
	at com.datasqrl.frontend.SqrlPlan.plan(SqrlPlan.java:47)
	at com.datasqrl.frontend.SqrlPlan.plan(SqrlPlan.java:40)
	at com.datasqrl.compile.Compiler.run(Compiler.java:125)
	at com.datasqrl.cmd.AbstractCompilerCommand.runCommand(AbstractCompilerCommand.java:108)
	at com.datasqrl.cmd.AbstractCommand.run(AbstractCommand.java:27)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.datasqrl.DatasqrlCMD.main(DatasqrlCMD.java:12)
```

**Comment by henneberger** [comment]
Resolved when moved to calcite parser
