### ISSUE TITLE
Stream table throws error 

### ISSUE THREAD

**Issue by henneberger** [DataSQRL/sqrl#271]
NewUpvotes throws the following error:

Recreating in the query in the stream statement is a workaround. 
```
java.lang.IllegalArgumentException: Underlying table is already a stream
	at com.datasqrl.error.ErrorMessage.asException(ErrorMessage.java:46)
	at com.datasqrl.error.ErrorCollector.exception(ErrorCollector.java:171)
	at com.datasqrl.error.ErrorCollector.fatal(ErrorCollector.java:158)
	at com.datasqrl.error.ErrorCollector.checkFatal(ErrorCollector.java:176)
	at com.datasqrl.plan.rules.SQRLLogicalPlanRewriter.makeStream(SQRLLogicalPlanRewriter.java:1434)
	at com.datasqrl.plan.rules.SQRLLogicalPlanRewriter.visit(SQRLLogicalPlanRewriter.java:1430)
```

SQRL:
```sql
IMPORT schema.createPost AS Post;
IMPORT schema.addUpvote AS Upvote;

Post.upvotes := JOIN Upvote u ON @.id = u.id;
Post.upvote := SELECT COALESCE(count(*), 0) AS upvotes
               FROM @.upvotes;

NewUpvotes := STREAM ON UPDATE AS
  SELECT * FROM Post.upvote;

EXPORT NewUpvotes TO schema.upvoteUpdated;
EXPORT Post TO schema.newPost;
```

Graphql:
```graphql
type Query {
  allPosts: [Post]
}

type Mutation {
  createPost(event: CreatePost!): PostResult
  addUpvote(event: UpvotePost!): UpvoteResult
}

input UpvotePost {
  id: String
}

type Subscription {
  newPost: Post
  upvoteUpdated: Upvote
}

type UpvoteResult {
  id: String
}

type Upvote {
  id: String
  upvote: Int
}

type PostResult {
  id: String
  title: String
  author: String
  url: String
}

type Post {
  id: String
  title: String
  author: String
  url: String
  upvote: PostUpvoteCount
}

type PostUpvoteCount {
  upvotes: Int
}
type UpvoteCount {
  upvotes: Int
}

input CreatePost {
  id: String
  title: String
  author: String
  url: String
}
```

**Comment by henneberger** [comment]
Stream syntax is deprecated. We can reopen this if it is a nested query issue.
