### ISSUE TITLE
Assigning deeply nested field throws exception during plan rewriting

### ISSUE THREAD

**Issue by henneberger** [DataSQRL/sqrl#276]
Sqrl Script:
```sql
IMPORT Product;
Product.rel := SELECT * FROM Product;
Product.rel.rel := SELECT * FROM Product;
Product.rel.rel.productidPlusOne := productid+1;
```

Error:
```
java.lang.ArrayIndexOutOfBoundsException: Index 25 out of bounds for length 19

	at org.apache.flink.calcite.shaded.com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:75)
	at org.apache.calcite.rex.RexBuilder.makeInputRef(RexBuilder.java:869)
	at com.datasqrl.util.SqrlRexUtil.maxOfTwoColumnsNotNull(SqrlRexUtil.java:318)
	at com.datasqrl.plan.rules.SQRLLogicalPlanRewriter.visit(SQRLLogicalPlanRewriter.java:985)
	at org.apache.calcite.rel.logical.LogicalJoin.accept(LogicalJoin.java:184)
	at com.datasqrl.plan.rules.SQRLLogicalPlanRewriter.visit(SQRLLogicalPlanRewriter.java:433)
	at org.apache.calcite.rel.logical.LogicalProject.accept(LogicalProject.java:132)
	at com.datasqrl.plan.rules.SQRLConverter.convert(SQRLConverter.java:29)
	at com.datasqrl.plan.local.generate.StatementSQRLConverter.convertToVanillaSQL(StatementSQRLConverter.java:55)
	at com.datasqrl.plan.local.generate.StatementSQRLConverter.convert(StatementSQRLConverter.java:31)
	at com.datasqrl.plan.local.generate.AbstractQueryStatementResolver.resolve(AbstractQueryStatementResolver.java:37)
	at com.datasqrl.plan.local.generate.StatementProcessor.visit(StatementProcessor.java:73)
	at com.datasqrl.plan.local.generate.StatementProcessor.visit(StatementProcessor.java:19)
	at org.apache.calcite.sql.QueryAssignment.accept(QueryAssignment.java:47)
	at com.datasqrl.frontend.fluent.Sqrl.planStatement(Sqrl.java:146)
	at com.datasqrl.frontend.fluent.Sqrl.addStatement(Sqrl.java:160)
```

**Comment by henneberger** [comment]
No longer an issue.
