### ISSUE TITLE
Source Mapping throws exception at line boundary

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#290]
Getting this error:
```
com.datasqrl.parse.ParsingException: line 22:27: mismatched input at '.'. Expecting: ',', 'FROM'
	at com.datasqrl.parse.ParsingErrorHandler.syntaxError(ParsingErrorHandler.java:117)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:377)
	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:275)
	at com.datasqrl.parse.SqlBaseParser.querySpecification(SqlBaseParser.java:2270)
	at com.datasqrl.parse.SqlBaseParser.queryPrimary(SqlBaseParser.java:2073)
	at com.datasqrl.parse.SqlBaseParser.queryTerm(SqlBaseParser.java:1959)
	at com.datasqrl.parse.SqlBaseParser.queryNoWith(SqlBaseParser.java:1819)
	at com.datasqrl.parse.SqlBaseParser.query(SqlBaseParser.java:1763)
	at com.datasqrl.parse.SqlBaseParser.statement(SqlBaseParser.java:769)
	at com.datasqrl.parse.SqlBaseParser.script(SqlBaseParser.java:203)
	at com.datasqrl.parse.SqrlParserImpl.invokeParser(SqrlParserImpl.java:120)
	at com.datasqrl.parse.SqrlParserImpl.parse(SqrlParserImpl.java:75)
	at com.datasqrl.parse.SqrlParserImpl.parse(SqrlParserImpl.java:68)
	at com.datasqrl.packager.ImportExportAnalyzer.analyze(ImportExportAnalyzer.java:32)
	at com.datasqrl.packager.Packager.lambda$inferDependencies$1(Packager.java:107)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:553)
	at com.datasqrl.packager.Packager.inferDependencies(Packager.java:108)
	at com.datasqrl.packager.Packager.populateBuildDir(Packager.java:83)
	at com.datasqrl.cmd.AbstractCompilerCommand.runCommand(AbstractCompilerCommand.java:69)
	at com.datasqrl.cmd.AbstractCommand.run(AbstractCommand.java:27)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.datasqrl.DatasqrlCMD.main(DatasqrlCMD.java:12)
java.lang.IllegalArgumentException: Invalid offset [1] for: 
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:326)
	at com.datasqrl.error.SourceMapImpl.getRange(SourceMapImpl.java:25)
	at com.datasqrl.error.ErrorPrinter.prettyPrint(ErrorPrinter.java:56)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.datasqrl.error.ErrorPrinter.prettyPrint(ErrorPrinter.java:25)
	at com.datasqrl.error.ErrorPrinter.prettyPrint(ErrorPrinter.java:19)
	at com.datasqrl.cmd.AbstractCommand.run(AbstractCommand.java:38)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.datasqrl.DatasqrlCMD.main(DatasqrlCMD.java:12)
```

For this script:
```
IMPORT source.Customers;
IMPORT source.Applications;
IMPORT source.Application_updates AS ApplicationUpdates;
IMPORT source.Loan_types AS LoanTypes;

Customers := DISTINCT Customers ON id ORDER BY updated_on DESC;
Applications := DISTINCT Applications ON id ORDER BY updated_at DESC;
LoanTypes := DISTINCT LoanTypes ON id ORDER BY updated_at DESC;

Customers.applications := JOIN Applications a ON @.id = a.customer_id ORDER BY a.application_date;

ApplicationUpdates.application := JOIN Applications a ON @.loan_application_id = a.id;
Applications.updates := JOIN ApplicationUpdates u ON @.id = u.loan_application_id ORDER BY u.timestamp;

Applications.loanType := JOIN LoanTypes t ON @.loan_type_id = t.id;

Customers.overview := SELECT a.loan_type_id, SUM(a.amount) as total_amount, COUNT(1) as total_loans
                      FROM @ JOIN @.applications a
                      GROUP BY a.loan_type_id;

ApplicationStatus := SELECT u.status, u.message, u.timestamp, a.id, a.customer_id, a.loan_type_id
                         a.amount, a.duration FROM ApplicationUpdates u JOIN u.application a;


Customers.recentFunding := SELECT SUM(a.amount) as total_amount, COUNT(1) as total_loans
                           FROM @ JOIN ApplicationStatus a ON @.id = a.customer_id
                           WHERE a.timestamp > now() - INTERVAL 21 DAY;

ApplicationAlert := SELECT a.id, a.customer_id, t.id, t.max_amount, t.min_amount, a.amount FROM ApplicationStatus a
                    JOIN LoanTypes t ON t.id = a.loan_type_id
                    WHERE a.amount > t.max_amount OR a.amount < t.min_amount;

```

**Comment by henneberger** [comment]
No longer an issue
