### ISSUE TITLE
Discovery issue with cardinality

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#338]
If for a field we have these 3 values in different records

  “null”

  null

 {"string":""}

Then after discovery the .schema.yml has:

  - name: "audit_src_uuid"

  columns:

  - name: "string"

    type: "STRING"

    tests:

    - "not_null"

  - name: " #value"

    type: "STRING"

  tests:

  - "cardianlity"

 

If we have just these 2 cases

  null

 {"string":""}

Then the .schema.yml ends up with:

  - name: "audit_src_uuid"

  columns:

  - name: "string"

    type: "STRING"

    tests:

    - "not_null"

  tests:

  - "cardianlity"

 

In both cases the discovery completes but the compilation fails with (same stack trace in both cases):

 

java.lang.IllegalArgumentException: Invalid integer value [null] for key [min]

                at com.datasqrl.error.ErrorMessage.asException(ErrorMessage.java:46)

                at com.datasqrl.error.ErrorCollector.exception(ErrorCollector.java:171)

                at com.datasqrl.error.ErrorCollector.fatal(ErrorCollector.java:158)

                at com.datasqrl.error.ErrorCollector.fatal(ErrorCollector.java:154)

                at com.datasqrl.schema.constraint.Cardinality$Factory.create(Cardinality.java:86)

                at com.datasqrl.schema.input.external.SchemaImport.convertConstraints(SchemaImport.java:176)

                at com.datasqrl.schema.input.external.SchemaImport.convert(SchemaImport.java:139)

                at com.datasqrl.schema.input.external.SchemaImport.convert(SchemaImport.java:124)

                at com.datasqrl.schema.input.external.SchemaImport.convert(SchemaImport.java:83)

                at com.datasqrl.schema.input.external.SchemaImport.convert(SchemaImport.java:75)

                at com.datasqrl.schema.input.FlexibleTableSchemaFactory.create(FlexibleTableSchemaFactory.java:39)

                at com.datasqrl.schema.input.FlexibleTableSchemaFactory.lambda$create$0(FlexibleTableSchemaFactory.java:31)

                at java.base/java.util.Optional.map(Optional.java:265)

                at com.datasqrl.schema.input.FlexibleTableSchemaFactory.create(FlexibleTableSchemaFactory.java:30)

                at com.datasqrl.loaders.ObjectLoaderImpl.loadTable(ObjectLoaderImpl.java:80)

                at com.datasqrl.loaders.ObjectLoaderImpl.load(ObjectLoaderImpl.java:60)

                at com.datasqrl.loaders.ObjectLoaderImpl.lambda$load$0(ObjectLoaderImpl.java:52)

                at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)

                at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)

                at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)

                at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)

                at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)

                at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

                at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)

                at com.datasqrl.loaders.ObjectLoaderImpl.load(ObjectLoaderImpl.java:53)

                at com.datasqrl.loaders.ModuleLoaderImpl.loadFromFileSystem(ModuleLoaderImpl.java:51)

                at com.datasqrl.loaders.ModuleLoaderImpl.getModule(ModuleLoaderImpl.java:26)

                at com.datasqrl.loaders.ModuleLoaderComposite.getModule(ModuleLoaderComposite.java:21)

                at com.datasqrl.plan.local.generate.ImportStatementResolver.getModule(ImportStatementResolver.java:124)

                at com.datasqrl.plan.local.generate.ImportStatementResolver.resolve(ImportStatementResolver.java:39)

                at com.datasqrl.plan.local.generate.StatementProcessor.visit(StatementProcessor.java:48)

                at com.datasqrl.plan.local.generate.StatementProcessor.visit(StatementProcessor.java:20)

                at org.apache.calcite.sql.ImportDefinition.accept(ImportDefinition.java:107)

                at com.datasqrl.plan.local.generate.Resolve.executeStatement(Resolve.java:64)

                at com.datasqrl.plan.local.generate.Resolve.lambda$planTablesHelper$1(Resolve.java:55)

                at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)

                at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)

                at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)

                at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)

                at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)

                at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)

                at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)

                at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

                at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)

                at com.datasqrl.plan.local.generate.Resolve.planTablesHelper(Resolve.java:55)

                at com.datasqrl.plan.local.generate.Resolve.planTables(Resolve.java:44)

                at com.datasqrl.frontend.SqrlPlan.plan(SqrlPlan.java:53)

                at com.datasqrl.frontend.SqrlPlan.plan(SqrlPlan.java:38)

                at com.datasqrl.compile.Compiler.run(Compiler.java:121)

                at com.datasqrl.cmd.AbstractCompilerCommand.runCommand(AbstractCompilerCommand.java:77)

                at com.datasqrl.cmd.AbstractCommand.run(AbstractCommand.java:29)

                at picocli.CommandLine.executeUserObject(CommandLine.java:2026)

                at picocli.CommandLine.access$1500(CommandLine.java:148)

                at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)

                at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)

                at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)

                at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)

                at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)

                at picocli.CommandLine.execute(CommandLine.java:2170)

                at com.datasqrl.DatasqrlCMD.main(DatasqrlCMD.java:12)

 

If I manually change the .schema.yml to the way it was discovered before I put back the “string” casting

  - name: "audit_src_uuid"

  type: "STRING"

  tests:

  - "not_null"

**Comment by henneberger** [comment]
Closing in preference for #549
