### ISSUE TITLE
Issue with TEXT index

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#471]
When running the conference example, I get:
```
java.lang.IllegalStateException: TEXT
	at com.datasqrl.engine.database.relational.IndexSelectorConfigByDialect.relativeIndexCost(IndexSelectorConfigByDialect.java:83)
	at com.datasqrl.plan.global.IndexSelector.costLess(IndexSelector.java:153)
	at com.datasqrl.plan.global.IndexSelector.optimizeIndexesWithCostMinimization(IndexSelector.java:133)
	at com.datasqrl.plan.global.IndexSelector.optimizeIndexes(IndexSelector.java:92)
	at com.datasqrl.plan.global.IndexSelector.optimizeIndexes(IndexSelector.java:61)
	at com.datasqrl.plan.global.DAGAssembler.assemble(DAGAssembler.java:169)
	at com.datasqrl.plan.global.DAGPlanner.assemble(DAGPlanner.java:86)
	at com.datasqrl.plan.global.DAGPlanner.plan(DAGPlanner.java:95)
	at com.datasqrl.frontend.SqrlOptimizeDag.planDag(SqrlOptimizeDag.java:50)
	at com.datasqrl.compile.Compiler.run(Compiler.java:173)
	at com.datasqrl.cmd.AbstractCompilerCommand.compilePackage(AbstractCompilerCommand.java:108)
	at com.datasqrl.cmd.AbstractCompilerCommand.runCommand(AbstractCompilerCommand.java:80)
	at com.datasqrl.cmd.AbstractCommand.run(AbstractCommand.java:30)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.datasqrl.DatasqrlCMD.main(DatasqrlCMD.java:12)
[FATAL] TEXT
```

**Comment by mbroecheler** [comment]
this has been fixed
