### ISSUE TITLE
Reference fully qualified function names in sqrl scripts

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#553]
When I try to reference a function by fully qualified name I get this assertion error:
```
java.lang.AssertionError
	at org.apache.calcite.sql.SqlIdentifier.getSimple(SqlIdentifier.java:328)
	at com.datasqrl.calcite.OperatorTable.lookupOperatorOverloads(OperatorTable.java:30)
	at com.datasqrl.calcite.SqrlToSql$1.visit(SqrlToSql.java:256)
	at com.datasqrl.calcite.SqrlToSql$1.visit(SqrlToSql.java:251)
	at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:139)
	at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:134)
	at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:101)
	at org.apache.calcite.sql.SqlOperator.acceptCall(SqlOperator.java:879)
	at org.apache.calcite.sql.SqlAsOperator.acceptCall(SqlAsOperator.java:123)
	at org.apache.calcite.sql.util.SqlShuttle.visit(SqlShuttle.java:66)
	at com.datasqrl.calcite.SqrlToSql$1.visit(SqrlToSql.java:270)
	at com.datasqrl.calcite.SqrlToSql$1.visit(SqrlToSql.java:251)
	at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:139)
	at com.datasqrl.calcite.SqrlToSql.hasAggs(SqrlToSql.java:251)
	at com.datasqrl.calcite.SqrlToSql.visitQuerySpecification(SqrlToSql.java:100)
	at com.datasqrl.calcite.SqrlToSql.visitQuerySpecification(SqrlToSql.java:68)
	at com.datasqrl.calcite.visitor.SqlNodeVisitor.accept(SqlNodeVisitor.java:80)
	at com.datasqrl.calcite.SqrlToSql.rewrite(SqrlToSql.java:93)
	at com.datasqrl.plan.validate.ScriptPlanner.postvisit(ScriptPlanner.java:323)
	at com.datasqrl.plan.validate.ScriptPlanner.visit(ScriptPlanner.java:306)
	at com.datasqrl.plan.validate.ScriptPlanner.visit(ScriptPlanner.java:111)
	at com.datasqrl.calcite.visitor.SqlNodeVisitor.accept(SqlNodeVisitor.java:42)
	at com.datasqrl.plan.validate.ScriptPlanner.validateStatement(ScriptPlanner.java:956)
	at com.datasqrl.plan.validate.ScriptPlanner.plan(ScriptPlanner.java:988)
	at com.datasqrl.compile.CompilationProcess.executeCompilation(CompilationProcess.java:59)
	at com.datasqrl.cmd.AbstractCompilerCommand.execute(AbstractCompilerCommand.java:116)
	at com.datasqrl.cmd.AbstractCompilerCommand.execute(AbstractCompilerCommand.java:76)
	at com.datasqrl.cmd.AbstractCommand.run(AbstractCommand.java:26)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.datasqrl.AbstractAssetSnapshotTest.execute(AbstractAssetSnapshotTest.java:104)
	at com.datasqrl.AbstractUseCaseTest.testUsecase(AbstractUseCaseTest.java:56)
	at com.datasqrl.UseCaseTest.testUsecase(UseCaseTest.java:19)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
```

For example (based on seedshop-teaser.sqrl):
```
IMPORT seedshop.Orders;

Orders.total := quantity * unit_price - coalesce(discount, 0.0);

CustomerSpending := SELECT customerid, time.endOfWeek(time) AS week,
    sum(total) AS total, sum(coalesce(discount, 0.0)) AS saved
  FROM Orders GROUP BY customerid, week ORDER BY week DESC;

ProductRevenue := SELECT productid, time.endOfWeek(time) AS week,
    sum(total) AS revenue
  FROM Orders GROUP BY productid, week ORDER BY week DESC;
```

**Comment by mbroecheler** [comment]
this won't be supported as we are using to Flink UDF handling.
