### ISSUE TITLE
CLI --api flag throws error

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#658]
When running the compiler with the `--api graphql` argument, I get:
```
java.nio.file.NoSuchFileException: build/schema.graphqls
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:548)
        at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
        at java.base/java.nio.file.Files.copy(Files.java:1295)
        at com.datasqrl.cmd.AbstractCompilerCommand.addGraphql(AbstractCompilerCommand.java:150)
        at com.datasqrl.cmd.AbstractCompilerCommand.execute(AbstractCompilerCommand.java:112)
        at com.datasqrl.cmd.AbstractCompilerCommand.execute(AbstractCompilerCommand.java:64)
        at com.datasqrl.cmd.AbstractCommand.run(AbstractCommand.java:26)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at com.datasqrl.DatasqrlCMD.main(DatasqrlCMD.java:13)
java.nio.file.NoSuchFileException: build/schema.graphqls
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:548)
        at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
        at java.base/java.nio.file.Files.copy(Files.java:1295)
        at com.datasqrl.cmd.AbstractCompilerCommand.addGraphql(AbstractCompilerCommand.java:150)
        at com.datasqrl.cmd.AbstractCompilerCommand.execute(AbstractCompilerCommand.java:112)
        at com.datasqrl.cmd.AbstractCompilerCommand.execute(AbstractCompilerCommand.java:64)
        at com.datasqrl.cmd.AbstractCommand.run(AbstractCommand.java:26)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at com.datasqrl.DatasqrlCMD.main(DatasqrlCMD.java:13)
[FATAL] build/schema.graphqls
```

**Comment by henneberger** [comment]
Appears to work now
